### ISSUE TITLE
BUG! Group formats wont work!

### ISSUE THREAD

**Issue by Bowle251** [OnCode9/LPC#1]
Heyy,, I have a problem where group formats wont work.. Im using LP as groupmanager. Cant get the placeholder "%luckperms_in_group% group" to work.. I am sure it is just that im using it wrong... Can you help me? Please show with config.yml
This is my try: https://gyazo.com/7413168512c51737d872848252e04595
I have Downloaded LuckPerms in PAPI

**Comment by OnCode9** [comment]
Hey, the proper usage of the placeholder you want to use is: '%luckperms_in_group_<group>%' (you can find LuckPerms placeholdrs here - https://api.extendedclip.com/expansions/luckperms/). So, your config should look sth like this: https://i.imgur.com/rxh0v3r.png Btw, you can use built-in in my plugin prefix placeholder '{prefix}' instead of %luckperms_prefix%, like this: https://i.imgur.com/oS952Rr.png Moreover, I hope you have PAPI installed and LuckPerms expansion downloaded, it is necessary for the PAPI placeholders to be used. Last but not least, rember to format your YAML file correctly. When you add a format for a new group ALWAYS keep 2 spaces in front of it. You can use http://www.yamllint.com/ to check, if you don't have any mistakes in the formatting. If you need more help, feel free to ask :)

**Comment by Bowle251** [comment]
Its kinda working working...
This is how it looks now: https://gyazo.com/cda6cfef7d3fa583b41e64e973013d6c
But there is an Yes before the prefix How to remove that?: https://gyazo.com/499118507a4c7a9cabbd8619aefdffa3

**Comment by OnCode9** [comment]
Remove luckperms_in_group placeholder. You don't need it. It just tell you whether the player is in the group you specified or not. If you need only a prefix, your config should look similar to this: https://i.imgur.com/lQuRmFp.png

**Comment by Bowle251** [comment]
All good :D

**Comment by OnCode9** [comment]
Great 👍
